# Main configuration template for MEV The OG
network: "mainnet"    # Network to operate on: "mainnet", "sepolia", etc.
mode: "test"          # "test" or "live"
dashboard:
  port: 8501          # Port for the dashboard (optional)

rpc:
  mainnet:
    primary: "https://eth-mainnet.alchemyapi.io/v2/your-api-key"
    fallback: "https://mainnet.infura.io/v3/your-infura-key"
  sepolia:
    primary: "https://eth-sepolia.g.alchemy.com/v2/your-api-key"

risk:
  max_drawdown_pct: 5      # Stop trading if drawdown > 5%
  max_loss_usd: 200        # Stop if USD loss > 200

alpha:
  enabled: ["cross_chain", "l2_sandwich"]   # List of enabled strategies
  params:
    cross_chain:
      min_profit_usd: 20
      max_slippage: 0.003
    l2_sandwich:
      gas_boost: true
      sandwich_depth: 2

notifier:
  telegram:
    enabled: true
    chat_id: "123456789"   # Your Telegram chat ID (do not store the token here)
    notify_on: ["error", "trade", "kill_switch"]

signer:
  type: "local"           # "local" or "cloud_kms"
  endpoint: "http://localhost:8000"   # If using a local signer service
  key_id: "prod-mev-bot-key"          # If using cloud KMS

ai:
  mutation_frequency: 10        # mutate params every N cycles
  decay_threshold: -0.01        # prune strategies below this score
  scoring:
    winrate_weight: 0.5
    pnl_weight: 0.5
    fail_weight: 0.1

# Add more config sections as needed for future strategies
